export const MOVIES_UPDATE_LIST = 'MOVIES_UPDATE_LIST'
export const MOVIES_UPDATE_FETCHING = 'MOVIES_UPDATE_FETCHING'
export const MOVIES_UPDATE_SELECTED = 'MOVIES_UPDATE_SELECTED'
export const MOVIES_UPDATE_PAGINATION = 'MOVIES_UPDATE_PAGINATION'
